name: Run Botcheck Go

on: [workflow_dispatch] # Define when to run the workflow

jobs:
  botcheck-node:
    runs-on: ubuntu-latest # Specify the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x' # Specify the Node.js version

    - name: Install dependencies
      working-directory: ./simple-click-chromedp
      run: |
        go get .
        go get -u github.com/chromedp/chromedp

    - name: Run Botcheck
      working-directory: ./simple-click-chromedp
      run: go run someclick.go



