name: Run Botcheck Go

on: [workflow_dispatch] # Define when to run the workflow

jobs:
  botcheck-node:
    runs-on: ubuntu-latest # Specify the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Node.js
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x' # Specify the Node.js version



